### ISSUE TITLE
运行报错了， 都不维护了吗？？lampClassic模块

### ISSUE THREAD

**Issue by Tuzhiqiang1996** [TuyaInc/tuya-panel-kit-template#7]
希望大佬可以看到！！！

**Comment by ShinyLeee** [comment]
提供下报错信息

**Comment by Tuzhiqiang1996** [comment]
![image](https://user-images.githubusercontent.com/57666259/92565022-a84aea00-f2ac-11ea-99aa-b6e1c7d4e2f4.png)

**Comment by Tuzhiqiang1996** [comment]
![image](https://user-images.githubusercontent.com/57666259/92565365-1c858d80-f2ad-11ea-9e2e-db9f5a966cfe.png)
我修改成这样 可以运行了

**Comment by ShinyLeee** [comment]
已修复，感谢反馈
